poke/urls.py
from django.urls import path
from .views import UserLogin, UserLogout, UserRegister, Choice, Chosen, UsersAllApi


app_name = 'poke'

urlpatterns = [
    path('', UserLogin.as_view(), name='login'),
    path('logout', UserLogout.as_view(), name='logout'),
    path('register', UserRegister.as_view(), name='register'),
    path('choice', Choice.as_view(), name='choice'),
    path('chosen/<str:name>', Chosen.as_view(), name='chosen'),
    path('api/v1', UsersAllApi.as_view(), name='restapi'),

]

poketest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poke.urls'))

]

poke/models.py
from django.db import models
from django.contrib.auth.models import User


class PokemonModel(models.Model):
    custumer = models.ForeignKey(User, on_delete=models.CASCADE)
    pokemon = models.CharField(verbose_name='Pokemon', max_length=100, default='')
    pokemon_url = models.CharField(verbose_name='Pokemon_url', unique=True,
                                   max_length=100, default='')

poke/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterFormUser(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

poke/views.py
from rest_framework import generics as apigeneric
from .forms import RegisterFormUser
from django.contrib.auth.views import LoginView, LogoutView
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import PokemonModel
import requests
import json
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy
from .serializers import PokeModelSerializer


class UserLogin(LoginView):
    template_name = 'login.html'


class UserLogout(LogoutView):
    template_name = 'login.html'


class UserRegister(generic.CreateView):
    template_name = 'register.html'
    form_class = RegisterFormUser
    success_url = '/'


class Choice(LoginRequiredMixin, generic.ListView):
    """pokemon status logic implementation and pagination
    as well as displaying a table of selected pokemon
    """

    login_url = '/'
    model = PokemonModel
    template_name = 'choice.html'

    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        offset = request.GET.get('offset')
        r = requests.get(f'https://pokeapi.co/api/v2/pokemon?offset={offset}&limit=10')
        pokemons = json.loads(r.content.decode('utf-8'))['results']
        for item in pokemons:
            if PokemonModel.objects.filter(pokemon=item['name']).count() >= 1:
                item['state'] = 'BUZY'
            else:
                item['state'] = 'FREE'
        next = json.loads(r.content.decode('utf-8'))['next'].split('?')[-1]
        prew = None
        if json.loads(r.content.decode('utf-8'))['previous']:
            prew = json.loads(r.content.decode('utf-8'))['previous'].split('?')[-1]
        return self.render_to_response({'pokes': pokemons,
                                        'my_pokes': PokemonModel.objects.filter(custumer=request.user),
                                        'next': next,
                                        'previous': prew})



class Chosen(LoginRequiredMixin, generic.View):
    """The same Pokemon cannot be selected by
    different players or multiple times
    I Use try: and except: constructions"""

    login_url = 'poke:login'

    def get(self, request, *args, **kwargs):
        try:
            PokemonModel.objects.get_or_create(custumer=self.request.user,
                                            pokemon=self.kwargs['name'],
                                           pokemon_url=self.kwargs['name'])
        except:
            pass
        return HttpResponseRedirect(reverse_lazy('poke:choice'))


class UsersAllApi(apigeneric.ListAPIView):
    """ API output of all players and their Pokémons"""
    queryset = PokemonModel.objects.all()
    serializer_class = PokeModelSerializer

templates/choice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p> личный кабинет </p>
    <a href="{% url 'poke:logout' %}">Выход</a>
    <h1>Выберите покемона</h1>
<div>
<table border="1">
    <caption>Таблица покемона</caption>
     <tr>
        <th>Имя покемона</th>
        <th>Навыки</th>
        <th>Статус</th>
     </tr>
    {% for p in pokes %}
        <tr> <td>{{ p.name }}</td><td><a href="{{ p.url }}"> {{ p.url }}</a> </td><td>{{ p.state }}</td>
            <td><a href="{% url 'poke:chosen' p.name %}"><button>Выбрать</button> </a> </td>
        </tr>
    {% endfor %}
</table >
    <a href="?{{ previous }}"><button>Previous page</button></a>
    <a href="?{{ next }}"><button>Next page</button></a>
<h1>Мои покемоны</h1>
<table border="1">
        <th>Имя покемона</th>
    {% for item in my_pokes %}
            <tr> <td><a href="{{ item.pokemon_url }}"> {{ item.pokemon_url }}</a> </td>
            </tr>
    {% endfor %}

</table>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pokeapi</title>
</head>
<body>
        <h1>Login</h1>
        <form method="POST">
            {% csrf_token %}

            {{ form }}
            <button type="submit">Войти</button>
        </form>
        <a href="{% url 'poke:register' %}"><button>Register</button></a>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Poke</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Register</button>
</form>
</body>
</html>